apiVersion: v1
kind: Pod
metadata:
  name: test-workload
  namespace: default
spec:
  serviceAccountName: default
  containers:
  - name: test
    image: ubuntu
    command: ["sleep", "3600"]
    volumeMounts:
    - name: spire-agent-socket
      mountPath: /run/spire/sockets
      readOnly: true
  volumes:
  - name: spire-agent-socket
    hostPath:
      path: /run/spire/sockets