apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire
data:
  agent.conf: |
    agent {
      server_address = "spire-server.spire.svc.cluster.local"
      server_port = "8081"
      trust_domain = "example.org"
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      insecure_bootstrap = true
      socket_path = "/run/spire/sockets/agent.sock"
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "minikube"
          token_path = "/var/run/secrets/tokens/spire-agent"
        }
      }

      KeyManager "memory" {
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
        }
      }
    }